name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: ubuntu-22.04
    outputs:
      docker-image: ${{ steps.create-tag.outputs.docker-image }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: create-tag
        run: echo "docker-image=${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.create-tag.outputs.docker-image }}
          cache-from: type=gha
          cache-to: type=gha

  unittests:
    needs:
      - setup-runner

    runs-on: ubuntu-22.04

    container:
      image: ${{ needs.setup-runner.outputs.docker-image }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls
          ./entrypoint.sh test
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          args: |
            npm run build
