name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-runner:
    runs-on: ubuntu-22.04

    outputs:
      docker-image: ${{ steps.create-tag.outputs.docker-image }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: create-tag
        run: echo "docker-image=ghcr.io/${{ github.repository }}:benchmark" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.create-tag.outputs.docker-image }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max


  unittests1:
    needs:
      - setup-runner

    runs-on: ubuntu-22.04

    container:
      image: ${{ needs.setup-runner.outputs.docker-image }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls
          pytest test/test.py
  unittests2:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          pip install -r requirements.txt
          pytest test/test.py
